[project]
name = "papyrus-pal"
version = "0.0.1"
description = "Your friend for Skyrim script authoring!"
authors = [
    {name = "Mrowr Purr",email = "mrowr.purr@gmail.com"}
]
license = {text = "0BSD"}
readme = "README.md"
requires-python = "<3.14,>=3.9"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
